### ISSUE TITLE
[Feature Request] reverse default colors

### ISSUE THREAD

**Issue by ubone** [M-Reimer/togglewebsitecolors#1]
Hello M-Reimer

Thank you for the great functionality for post 57 Firefox

A version with black background and white foreground would be highly useful as well.

Would you consider to either:

* add a simple toggle button in the addon's page (the manifest.json?) to flip the colors
* or maybe release a sister addon on [addons.mozilla.org](https://addons.mozilla.org/) with those colors

      diff --git a/nocolors.css b/nocolors.css
      index 5683545..3871cac 100644
      --- a/nocolors.css
      +++ b/nocolors.css
      @@ -1,9 +1,9 @@
       * {
      -  color: black !important;
      -  background: white !important;
      +  color: white !important;
      +  background: black !important;
       }
       a, a * {
      -  color: blue !important;
      +  color: green !important;
       }

       img, p {

Thank you again.

**Comment by M-Reimer** [comment]
I would prefer to not make the addon too bloated.
And I won't create a "sister" addon either.
This addon was meant to replace the "Colors" checkbox on PrefBar and to be used occasionally on pages which use horrible design and are difficult to read.
Why do you need the colors inverted?

**Comment by ubone** [comment]
Many LCDs use PWM to control brightness levels. Because of that we use 100% brightness which is ok during the day but can be a bit too much at night.

https://addons.mozilla.org/en-US/firefox/addon/toggledocumentcolors-198916/
This addon made it easy to have #000 bg and #ccc fg for those occasions but is now legacy.

I agree your addon is nice as it is not bloated at all.

**Comment by M-Reimer** [comment]
I agree that custom colors could be a nice addition.
But I'll have to reconsider how much work this would be to add this. Especially as I have to keep within the possibilities of the WebExtensions API with this.
And it is also a bit dangerous to add too much possibilities. There is a risk that another user will request "color profiles" in a second stage which would finally go beyond the scope of the project goals I had in mind.

**Comment by M-Reimer** [comment]
Fixed in Version 2.0.0. With this version you may set your own colors.
