### ISSUE TITLE
Feature request: Reverse default on/off for urls in a config file.

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [M-Reimer/togglewebsitecolors#11]
Similar requests have been made, but this is simpler, clearer, more explicit, more limited, & probably easier to implement:

When a new tab is opened this could consult a simple config file, a plain text file, with urls, one to a line. If the url is on the list, the default behavior of on or off for new tabs would be reversed.

You don't have to add this to the gui. We can manage it with a text editor. For those who don't, won't, or can't, the behavior is unchanged - it becomes simply an effectively undocumented feature for them. You could implement this and it would be useful NOW - and if someone wants to extend the gui later, great. If not, no harm is done. For people who don't make the config file, this would work the same way it does now.

Thanks for considering it.

**Comment by M-Reimer** [comment]
Does not work at all. Sorry.

Every Add-on runs in its own sandbox for security and no, there is no way to access your hard drive (or better some arbitrary path on it) from inside this sandbox.

The only way to read and store settings would be to use the "Storage" API which is meant exactly for this purpose. And to use it, there is a GUI needed to create, modify, delete entries there.

Actually I'm not sure if it would be better to also close #6 as, as already described there, this is and never was the goal of this simple Add-on.

It is meant to toggle colors **per tab**. But a tab is not limited to one URL or domain. In fact usually you open a tab with no URL at all and then enter it into the URL bar. What should any kind of "white-/blacklist" do then? Toggle the setting over and over again while you are surfing?

I think what you need may be better solved with this one:
https://addons.mozilla.org/firefox/addon/styl-us/
