### ISSUE TITLE
Background is covering images on facebook & twitter

### ISSUE THREAD

**Issue by javi2man** [M-Reimer/togglewebsitecolors#12]
The extension is great but i've found that the backgroud color is covering the images on these web sites: m.facebook.com & mobile.twitter.com, on other pages works like a charm! I've installed it on firefox for android. It 's a light extension and does not slow down the firefox browser, keep improving it!

**Comment by M-Reimer** [comment]
Always provide example links and a before/after screenshot. I did a try and at least some pictures from some randomly picket pages seem to display just fine.

**Comment by javi2man** [comment]
The problem is with those particular pages @M-Reimer . Here are the screenshots

**Comment by javi2man** [comment]
![Screenshot_2021-09-19-08-30-55](https://user-images.githubusercontent.com/36956081/133926229-887feed6-47e8-440e-8f19-d9b3ee9b674f.png)
![Screenshot_2021-09-19-08-31-02](https://user-images.githubusercontent.com/36956081/133926260-61c8b0cd-d31e-4910-97d9-b44b3dbc1817.png)
![Screenshot_2021-09-19-08-38-17](https://user-images.githubusercontent.com/36956081/133926293-677c67ad-f17e-4681-8993-377ca5360019.png)
![Screenshot_2021-09-19-08-38-27](https://user-images.githubusercontent.com/36956081/133926317-4ac97cc8-cccf-404d-8c12-9e7db737fc7e.png)

**Comment by M-Reimer** [comment]
Please also post the URLs so I can do some tries myself.

**Comment by javi2man** [comment]
@M-Reimer The web site https://m.facebook.com doesn't show any wall 's pictures in general (but stories 's images are shown ok)
On https://mobile.twitter.com can't see any image at all with the addon

**Comment by M-Reimer** [comment]
At least for m.facebook.com I still need a direct link to test this out. It is impossible to "surf" their site without an account. I don't have one and I won't create one.

**Comment by javi2man** [comment]
@M-Reimer On https://mobile.twitter.com/ActionRetro1 (for example) I can't see any images even without an account, and on
https://m.facebook.com/ActionRetro/ (for example)
I first logged out for testing, and noticed that I can see the images but not the cover photo (screenshot)
![IMG_20210919_151418](https://user-images.githubusercontent.com/36956081/133938353-811b456e-c3f7-4ea7-a3c7-7e66996f3df8.jpg)
But if I am logged in, I can't see any images except for the stories. This is very strange and I don't know what could be due to

**Comment by M-Reimer** [comment]
Thanks for helping with fixing this issue. A new version is on its way.
