### ISSUE TITLE
Show difference between visited/not-visited link

### ISSUE THREAD

**Issue by HPGHEL** [M-Reimer/togglewebsitecolors#2]
Hi!

Thanks for this FF extension.  I hope I'm placing this in the right place, as I'm not really familiar with Github - so apologies if not.

I find this simple extension very helpful.  I also often want to be able to see quickly whether I've visited a link previously.  When I activate this addon on a tab, the text is a helpful black on white, and then the links are all blue.  If the visited ones could be a different colour (such as the classic red) this would really help with my use.  

I realise you don't really want to bloat this addon, which makes sense - but I just wanted to ask if there was any way I could get into settings to just change the colour of visited links?  I see in Github that there is a page of code, but firstly I didn't spot anything that did this - and secondly I don't know where this code would need to be placed - although if some code could accomplish this and you could let me know the location to place such code that would be fabulous.

Even if this isn't possible, thanks for your time.

**Comment by M-Reimer** [comment]
This is possible and part of my current work where it will be possible to edit the colors in the addon settings.

**Comment by M-Reimer** [comment]
Fixed in version 2.0.0
