### ISSUE TITLE
Issue: Visited link color not effect bug

### ISSUE THREAD

**Issue by SANJYSAN** [M-Reimer/togglewebsitecolors#4]
Hello:

This plug-in is pretty good but have a bug that the visited link is not effect.
When I change the Unvisited links color in link colors option on this addon's option page and refresh it, the visited links color's value will be change to the same color as Unvisited links color. 
When I chenge Visited links color option and refresh it, it's color's value will be reset to same as Unvisited links color.
And in Toggle Website Colors Addon triggered, the Visited links's color is not effect , it's color will same as the Unvisited links color even you have visited it.

When I read your source code in GitHub, I found this bug maybe here:

In file togglewebsitecolors/background.js
36    const link = prefs.link_color || "#0000EE";
37    const visited = prefs.**link_color** || "#551A8B";

In file togglewebsitecolors/options.js
48    let link = result.link_color || "#0000EE";
49    let visited = result.**link_color** || "#551A8B";

The const link and const visited both set by prefs.link_color, and the let link and let visited both set by prefs.link_color. This is not reasonable.

I think it shoud like this:

In file togglewebsitecolors/background.js
37    const visited = prefs.**visited_color** || "#551A8B";

In file togglewebsitecolors/options.js
49    let visited = result.**visited_color** || "#551A8B";

Best wishes.

by SANJYSAN.

**Comment by M-Reimer** [comment]
Thank you very much for analyzing this issue and pointing out the location of the problem.
An updated version (2.0.1) is on its way.
