### ISSUE TITLE
Transparent background to panels

### ISSUE THREAD

**Issue by vivasteve** [M-Reimer/togglewebsitecolors#5]
Hi - great add-on for people who use dark themes - thanks!
One suggestion:
panels, dropdowns, etc have transparent background - can also see content from below
maybe could be fixed with this change:
 * {
  color: $TEXTCOLOR !important;
  background: $BACKGROUNDCOLOR !important;
}
Thanks, Steve

**Comment by M-Reimer** [comment]
There are websites that need the transparent background. Making these parts opaque would make some text unreadable. Do you have an example URL?

**Comment by Swanth** [comment]
Hi. This is an issue for me too. I notice it most on pop-ups (e.g., login prompts) and menus. It's even happening on this page - there are lines showing up that don't appear with the default colors.
![gh_transparent](https://user-images.githubusercontent.com/42578862/44406920-ceb55580-a52a-11e8-8573-a620155a7bf0.JPG)

**Comment by vivasteve** [comment]
> There are websites that need the transparent background. Making these parts opaque would make some text unreadable. Do you have an example URL?

Look at this site
https://www.justwatch.com/us
When you click any of the drop downs, Release year, Genre, Price, etc, with togglewebsitecolors enabled, it is difficult to read the content because the background content is also visible.

Of course,  what I am suggesting may create other problems ...
Anyway I use this addon a lot - much appreciated!

**Comment by M-Reimer** [comment]
I had a look at the site "justwatch.com" and this is actually the perfect example why it may be bad to force a background color. If you do so and you "pop out" those menus, then the whole website is filled with the background color.

Fixing this seems to be beyond the capabilities of CSS styling.

**Comment by M-Reimer** [comment]
Especially if your goal is to disable colors for all websites by default, maybe this (more simple but also more limited) better fits your needs:
https://github.com/M-Reimer/toggleglobalcolors
Still takes some time for Mozilla to review but I think it will be available tomorrow.
It uses a Firefox built in feature (which works global only and not per tab!)
As Firefox has this inside its render code, it is not limited to changes that are possible with CSS.
