### ISSUE TITLE
Need white list or black list

### ISSUE THREAD

**Issue by SANJYSAN** [M-Reimer/togglewebsitecolors#6]
Hello,

Can you add a white list or black list option for this ToggleWebsiteColors addon ?
thanks!

**Comment by M-Reimer** [comment]
This would be not that easy. It requires rewrite of some code and even some kind of GUI to manage the white/blacklist.

IMHO this is not the target of this simple Addon. It was meant to be used for some rare cases where websites are unreadable in the original configuration. Maybe something like this can be added somewhere later in the future. I would also accept pull requests.

**Comment by M-Reimer** [comment]
I recommend this Add-on as alternative for everyone who needs "per domain" styling:

https://addons.mozilla.org/firefox/addon/styl-us/

My Add-on is meant to toggle colors **per tab** and usually inside a tab there could be no URL at all (when opening a new, empty, one) or the URL/domain may change while surfing which would effectively mean that the status of the Add-on would need to be toggled over and over again.

This is especially difficult if frames or iframes are used in websites.
