### ISSUE TITLE
keyboard shortcut

### ISSUE THREAD

**Issue by tiocfaidharla** [M-Reimer/togglewebsitecolors#7]
Hi, thanks for this extension, essential to all with sensitivity to light. This is not an 'issue' but would it be possible to assign a keyboard shortcut? It would help greatly especially in cases of transparent panel problems. TIA

**Comment by M-Reimer** [comment]
Would be possible but I don't really like the "static" mechanism for hotkeys. I'll have to have a deeper look into this. I had a "hotkey editor" for PrefBar and maybe this can be ported to WebExtensions, so users are able to define their own hotkey.

**Comment by tiocfaidharla** [comment]
Hi Manuel, thanks for the keyboard shortcut....but...how does it work?? All I can see is reset, do I need another extension to assign a shortcut? TIA
Mark

**Comment by M-Reimer** [comment]
There is a firefox standard feature for this:
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
The Mozilla developers just missed that it may be useful to be able to get rid of a set shortcut again. That's why all my addons have the "Reset" button built in.
