### ISSUE TITLE
Request: Toggle Document Font

### ISSUE THREAD

**Issue by Yaron10** [M-Reimer/togglewebsitecolors#8]
Hello Manuel,

I've seen some of your "Toggle" extensions for Firefox.
Thank you for your work.

I've recently upgraded from FF 52 to FF 64.
The feature I miss the most is a toolbar button to quickly toggle `browser.display.use_document_fonts`.
I'm not a professional developer and I don't have the strength to explore the new FF structure.

Do you know if such an extension exists?
If not, may I ask if you might be willing to create it? - I would highly appreciate it.

Best regards.
Yaron

**Comment by M-Reimer** [comment]
Sorry, but this request is off-topic here (no issue for "toggle webiste colors").
I don't need such an extension, but already have this on my list of "things to do if I find the required time".

**Comment by M-Reimer** [comment]
See: https://addons.mozilla.org/de/firefox/addon/togglefonts/

**Comment by Yaron10** [comment]
Thank you. :+1:
